# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "User" do
      optional :name, :string, 1
      optional :id, :int32, 2
      optional :email, :string, 3
    end
    add_message "GetUserReqProto" do
      optional :email, :string, 1
    end
    add_message "GetUserRespProto" do
      optional :user, :message, 1, "User"
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
GetUserReqProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetUserReqProto").msgclass
GetUserRespProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetUserRespProto").msgclass
